version: "3.7"

services:
  checkers-backend:
    image: checkersbackend:latest
    ports:
      - 3000:3000
    working_dir: /usr/src/checkers-backend
    volumes:
      - ./checkers-backend:/usr/src/checkers-backend

  checkers-frontend:
    image: checkersfrontend:latest
    ports:
      - 8080:80
    working_dir: /usr/src/checkers-frontend
    volumes:
      - ./checkers-frontend:/usr/src/checkers-frontend
